<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JobSeeder extends Seeder
{
    public function run(): void
    {
        $jobs = [
            [
                'title' => 'Senior UI/UX Designer',
                'company' => 'Stripe',
                'company_logo' => null,
                'location' => 'San Francisco, CA',
                'category' => 'Design',
                'type' => 'full-time',
                'salary_min' => 120000,
                'salary_max' => 160000,
                'description' => 'We are looking for a talented Senior UI/UX Designer to join our product team. You will be responsible for creating intuitive, user-centered designs for our financial products used by millions worldwide.',
                'requirements' => json_encode(['5+ years experience in UI/UX design', 'Proficiency in Figma and Adobe XD', 'Experience with design systems', 'Strong portfolio demonstrating end-to-end design process']),
                'is_featured' => true,
                'is_active' => true,
                'created_at' => now()->subDays(1),
                'updated_at' => now()->subDays(1),
            ],
            [
                'title' => 'Full Stack Developer',
                'company' => 'Shopify',
                'company_logo' => null,
                'location' => 'Remote',
                'category' => 'Technology',
                'type' => 'remote',
                'salary_min' => 100000,
                'salary_max' => 140000,
                'description' => 'Join Shopify\'s engineering team to build and scale the commerce platform that powers over 1 million businesses. You\'ll work on challenging technical problems with a team that values craftsmanship.',
                'requirements' => json_encode(['3+ years with React and Node.js', 'Experience with Ruby on Rails', 'Familiarity with GraphQL', 'Strong understanding of distributed systems']),
                'is_featured' => true,
                'is_active' => true,
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'title' => 'Product Marketing Manager',
                'company' => 'HubSpot',
                'company_logo' => null,
                'location' => 'Boston, MA',
                'category' => 'Marketing',
                'type' => 'full-time',
                'salary_min' => 90000,
                'salary_max' => 120000,
                'description' => 'HubSpot is seeking a Product Marketing Manager to drive go-to-market strategies for our CRM suite. You will partner with product, sales, and customer success to craft compelling narratives.',
                'requirements' => json_encode(['4+ years in B2B SaaS marketing', 'Experience with product launches', 'Strong analytical and writing skills', 'Data-driven mindset']),
                'is_featured' => true,
                'is_active' => true,
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subDays(3),
            ],
            [
                'title' => 'Data Scientist',
                'company' => 'Airbnb',
                'company_logo' => null,
                'location' => 'New York, NY',
                'category' => 'Finance',
                'type' => 'full-time',
                'salary_min' => 130000,
                'salary_max' => 180000,
                'description' => 'Join Airbnb\'s data science team to shape how we understand host and guest experiences. You\'ll build models that drive product decisions and help millions of people connect.',
                'requirements' => json_encode(['PhD or MS in Statistics, CS, or related field', 'Proficiency in Python and SQL', 'Experience with ML frameworks', 'Strong statistical knowledge']),
                'is_featured' => true,
                'is_active' => true,
                'created_at' => now()->subDays(4),
                'updated_at' => now()->subDays(4),
            ],
            [
                'title' => 'DevOps Engineer',
                'company' => 'Datadog',
                'company_logo' => null,
                'location' => 'Remote',
                'category' => 'Technology',
                'type' => 'remote',
                'salary_min' => 115000,
                'salary_max' => 155000,
                'description' => 'We\'re looking for a DevOps Engineer to help build and maintain the infrastructure that powers our monitoring platform. You\'ll work with cutting-edge cloud technologies at massive scale.',
                'requirements' => json_encode(['3+ years with AWS/GCP/Azure', 'Kubernetes and Docker expertise', 'Experience with Terraform', 'Strong scripting skills in Python or Go']),
                'is_featured' => false,
                'is_active' => true,
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(5),
            ],
            [
                'title' => 'iOS Developer',
                'company' => 'Duolingo',
                'company_logo' => null,
                'location' => 'Pittsburgh, PA',
                'category' => 'Technology',
                'type' => 'full-time',
                'salary_min' => 95000,
                'salary_max' => 130000,
                'description' => 'Help build the most downloaded language learning app in the world. You\'ll craft delightful mobile experiences that make learning fun for hundreds of millions of users globally.',
                'requirements' => json_encode(['3+ years Swift development', 'Strong understanding of iOS frameworks', 'Experience with animations and custom UI', 'Knowledge of A/B testing']),
                'is_featured' => false,
                'is_active' => true,
                'created_at' => now()->subDays(6),
                'updated_at' => now()->subDays(6),
            ],
            [
                'title' => 'HR Business Partner',
                'company' => 'Notion',
                'company_logo' => null,
                'location' => 'San Francisco, CA',
                'category' => 'Human Resource',
                'type' => 'full-time',
                'salary_min' => 85000,
                'salary_max' => 115000,
                'description' => 'Join Notion\'s People team to support our rapidly growing organization. You\'ll be a strategic partner to leaders, helping build the culture and processes that make Notion a great place to work.',
                'requirements' => json_encode(['5+ years HR experience in tech', 'PHR or SHRM certification preferred', 'Experience with HRIS systems', 'Strong employee relations skills']),
                'is_featured' => false,
                'is_active' => true,
                'created_at' => now()->subDays(7),
                'updated_at' => now()->subDays(7),
            ],
            [
                'title' => 'Frontend Engineer',
                'company' => 'Linear',
                'company_logo' => null,
                'location' => 'Remote',
                'category' => 'Technology',
                'type' => 'remote',
                'salary_min' => 110000,
                'salary_max' => 150000,
                'description' => 'Build the future of software development tools at Linear. You\'ll work on a product loved by thousands of engineering teams, focusing on performance, design, and developer experience.',
                'requirements' => json_encode(['3+ years React experience', 'Deep knowledge of CSS and web performance', 'Experience with TypeScript', 'Eye for design and attention to detail']),
                'is_featured' => true,
                'is_active' => true,
                'created_at' => now()->subDays(8),
                'updated_at' => now()->subDays(8),
            ],
            [
                'title' => 'Content Writer',
                'company' => 'Buffer',
                'company_logo' => null,
                'location' => 'Remote',
                'category' => 'Marketing',
                'type' => 'part-time',
                'salary_min' => 50000,
                'salary_max' => 70000,
                'description' => 'Create compelling content that helps small businesses grow their social media presence. You\'ll write blog posts, case studies, and guides that educate and inspire our audience.',
                'requirements' => json_encode(['2+ years content writing experience', 'Strong SEO knowledge', 'Experience with social media marketing', 'Portfolio of published work']),
                'is_featured' => false,
                'is_active' => true,
                'created_at' => now()->subDays(9),
                'updated_at' => now()->subDays(9),
            ],
            [
                'title' => 'Backend Engineer (Go)',
                'company' => 'Cloudflare',
                'company_logo' => null,
                'location' => 'Austin, TX',
                'category' => 'Technology',
                'type' => 'full-time',
                'salary_min' => 125000,
                'salary_max' => 170000,
                'description' => 'Help Cloudflare build the internet\'s security and performance layer. You\'ll work on highly distributed systems handling millions of requests per second.',
                'requirements' => json_encode(['4+ years backend development', 'Proficiency in Go or Rust', 'Experience with distributed systems', 'Understanding of networking and security']),
                'is_featured' => false,
                'is_active' => true,
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(10),
            ],
            [
                'title' => 'Graphic Designer',
                'company' => 'Figma',
                'company_logo' => null,
                'location' => 'San Francisco, CA',
                'category' => 'Design',
                'type' => 'full-time',
                'salary_min' => 80000,
                'salary_max' => 110000,
                'description' => 'Create stunning visual content for Figma\'s marketing and product teams. You\'ll design everything from social media assets to conference booth graphics.',
                'requirements' => json_encode(['3+ years graphic design experience', 'Expert in Figma and Illustrator', 'Strong brand identity skills', 'Experience with motion graphics a plus']),
                'is_featured' => false,
                'is_active' => true,
                'created_at' => now()->subDays(11),
                'updated_at' => now()->subDays(11),
            ],
            [
                'title' => 'Sales Development Representative',
                'company' => 'Salesforce',
                'company_logo' => null,
                'location' => 'Chicago, IL',
                'category' => 'Marketing',
                'type' => 'full-time',
                'salary_min' => 55000,
                'salary_max' => 80000,
                'description' => 'Kick-start your sales career at Salesforce, the world\'s #1 CRM. You\'ll prospect and qualify leads, helping enterprise companies discover the power of our platform.',
                'requirements' => json_encode(['1+ year in sales or customer-facing role', 'Excellent communication skills', 'Resilient and goal-oriented', 'CRM experience a plus']),
                'is_featured' => false,
                'is_active' => true,
                'created_at' => now()->subDays(12),
                'updated_at' => now()->subDays(12),
            ],
        ];

        DB::table('job_listings')->insert($jobs);

        $this->command->info('✅ ' . count($jobs) . ' jobs seeded successfully!');
    }
}
